// import { Challenge } from "./challenges.type";

// export const DEFAULT_MISSIONS: Array<Challenge> = [
//   {
//     id: "1",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
//   {
//     id: "2",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
//   {
//     id: "3",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
//   {
//     id: "4",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
//   {
//     id: "5",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
//   {
//     id: "6",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
//   {
//     id: "7",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
//   {
//     id: "8",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
//   {
//     id: "9",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
//   {
//     id: "10",
//     title: "Desafio Exemplo",
//     description: "Resolva problemas matemáticos básicos",
//     questionText: "Quanto é 8 + 5?",
//     answerOptions: ["13"],
//     correctAnswer: 0,
//     completed: false,
//     unlocked: true,
//   },
// ];

export interface Mission {
  id: string;
  title: string;
  description: string;
  completed: boolean;
  unlocked: boolean;
}

export const DEFAULT_MISSIONS: Mission[] = [
  {
    id: "1",
    title: "Primeiro Contato",
    description: "Converse com pelo menos 3 personagens diferentes",
    completed: false,
    unlocked: true,
  },
  {
    id: "2",
    title: "Explorador",
    description: "Visite todas as áreas do mapa",
    completed: false,
    unlocked: false,
  },
  {
    id: "3",
    title: "Colecionador",
    description: "Encontre 5 itens raros",
    completed: false,
    unlocked: false,
  },
  {
    id: "4",
    title: "Mestre das Habilidades",
    description: "Use todas as habilidades disponíveis",
    completed: false,
    unlocked: false,
  },
  {
    id: "5",
    title: "Amigo dos Animais",
    description: "Alimente 10 animais diferentes",
    completed: false,
    unlocked: false,
  },
  {
    id: "6",
    title: "Primeiro Contato",
    description: "Converse com pelo menos 3 personagens diferentes",
    completed: false,
    unlocked: true,
  },
  {
    id: "7",
    title: "Explorador",
    description: "Visite todas as áreas do mapa",
    completed: false,
    unlocked: false,
  },
  {
    id: "8",
    title: "Colecionador",
    description: "Encontre 5 itens raros",
    completed: false,
    unlocked: false,
  },
  {
    id: "9",
    title: "Mestre das Habilidades",
    description: "Use todas as habilidades disponíveis",
    completed: false,
    unlocked: false,
  },
  {
    id: "10",
    title: "Amigo dos Animais",
    description: "Alimente 10 animais diferentes",
    completed: false,
    unlocked: false,
  },
];
